In [1]:
!pip install couchdb
!pip install pandas

     |████████████████████████████████| 71kB 1.8MB/s eta 0:00:01


In [17]:
import couchdb
import time
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import json 
from pandas.io.json import json_normalize

In [3]:
# Read Access Credentials
with open("passwords.csv") as myfile:
    head = [next(myfile) for x in range(1)]
info = str(head[0]).split(',')
name = info[0]
pw = info[1]

In [4]:
# Connect to Server
secure_remote_server = couchdb.Server('https://'+name+':'+pw+'@couchdb3.prtd.app/')
db = secure_remote_server['anc5']

In [5]:
# Extract data (will take 5-10 minutes, recommend putting these lines in a separate cell)
rows = db.view('_all_docs', include_docs=True) # ,limit=10
data = [row['doc'] for row in rows]
df = pd.DataFrame(data)

In [13]:
# Separate out data types
analysis = df[df['_id'].str.contains("analysis")].reset_index()
book = df[df['_id'].str.contains("book")].reset_index()
sample = df[df['_id'].str.contains("sample")].reset_index()
institution = df[df['_id'].str.contains("institution")].reset_index()
person = df[df['_id'].str.contains("person")].reset_index()
paper = df[df['_id'].str.contains("paper")].reset_index()
catalog = df[df['_id'].str.contains("catalog")].reset_index()

# Data: Sample

def checkSitu(x,key):
    try:
        return x[key]
    except:
        return np.NaN

# Sample

In [ ]:
# Initial Setup
sample1 = sample.dropna(axis=1, how='all').drop('index', axis=1)
sample1['_id'] = sample1['_id'].str.replace('sample:','')

# Relabel columns
sample1.rename(columns={"_id": "sample_id"}, inplace=True)
sample1['objectId'] = sample1['objectId'].str.replace('book:','')
sample1.rename(columns={"objectId": "book_id"}, inplace=True)

#Separate out columns
sample2 = sample1[['sample_id','book_id', 'barcode', 'procedure', 'notes', 'inSitu', 'pageSampled']]

# Extract inSitu information
sample2['status']=sample2['inSitu'].apply(lambda x: checkSitu(x,'isInSitu'))
sample2['type']=sample2['inSitu'].apply(lambda x: checkSitu(x,'type'))
sample2['location']=sample2['inSitu'].apply(lambda x: checkSitu(x,'location'))
sample2['set']=sample2['inSitu'].apply(lambda x: checkSitu(x,'set'))

sample2

In [7]:
sample2.describe()

sample_id book_id barcode procedure notes  \
count         6227    6227    6227      6227  6227   
unique        6227     997    1082         1   359   
top     0000012871   10149               SOP         
freq             1      56    5146      6227  4583   

                                                   inSitu pageSampled status  \
count                                                6227        6227   6227   
unique                                                 26         246      2   
top     {'isInSitu': True, 'type': 'ftir', 'location':...         165   True   
freq                                                 1010         127   5146   

        type location   set  
count   5649     5649  5649  
unique     4        5     4  
top     fors     edge        
freq    3085     2023  5611

In [8]:
sample2['location'].unique()

array([nan, 'edge', 'inset', 'gutter', 'spot', ''], dtype=object)

In [10]:
sample2['set'].unique()

array([nan, '', '1', '2', '3'], dtype=object)

In [11]:
sample2['type'].unique()

array([nan, 'fors', 'ftir', 'xrf', ''], dtype=object)

In [12]:
sample2['status'].unique()

array([False,  True])

In [105]:
#summary of the notes dataframe
notes_df = sample2[["sample_id", "notes"]]
notes_df2 = notes_df[notes_df.notes != '']
notes_df2.describe()

sample_id           notes
count         1644            1644
unique        1644             358
top     0000011708  opened already
freq             1              30

In [106]:
#split the notes value into a list on commas, periods, or new line charcters
notes_df2["notes"] = notes_df2["notes"].str.split(r",|\.|\/n")
notes_df2

sample_id                                              notes
41    0000010235  [Gatherings have conspicuously different degre...
42    0000010236  [Gatherings have conspicuously different degre...
43    0000010237  [Sections have very different degrees of stain...
44    0000010238  [Sections have very different degrees of stain...
88    0000010282  [Sections have very different degrees of stain...
...          ...                                                ...
6189  0000016399                                      [plate stock]
6198  0000016408                                       [text stock]
6199  0000016409                                      [plate stock]
6223  0000016433            [primary textblock paper,  plate stock]
6224  0000016434           [secondary textblock paper,  text stock]

[1644 rows x 2 columns]

In [96]:
#closer look at the new df
notes_df2.head(25)

sample_id                                              notes
41   0000010235  [Gatherings have conspicuously different degre...
42   0000010236  [Gatherings have conspicuously different degre...
43   0000010237  [Sections have very different degrees of stain...
44   0000010238  [Sections have very different degrees of stain...
88   0000010282  [Sections have very different degrees of stain...
89   0000010283  [Sections have very different degrees of stain...
98   0000010292  [Clear paper - makes up most of the book's gat...
109  0000010303  [Sections have very different degrees of stain...
155  0000010349                            [White textblock paper]
160  0000010354  [Two distinct paper types in this book,  This ...
162  0000010356  [Page 169 had pencil annotations in the margin, ]
167  0000010361                             [lighter/whiter stock]
170  0000010364  [unopened top edge was opened with scalpel to ...
171  0000010365  [unopened top edge was opened with scalpel to ...
173  0000010367  [Sections have very different degrees of stain...
174  0000010368                    [Brown paper for illustrations]
175  0000010369  [Two distinct paper types in this book,  This ...
176  0000010370                                      [cream stock]
190  0000010389  [London ed,  - 1 of 3 vol, s (Boston ed,  has ...
191  0000010390  [London ed,  - 2 of 3 vol, s (Boston ed,  has ...
192  0000010391  [London ed,  - 3 of 3 vol, s (Boston ed,  has ...
201  0000010400              [Lighter paper with less yellowing, ]
202  0000010401                          [Almost orange paper, \n]
203  0000010402              [Paper with little staining/foxing, ]
204  0000010403                [Paper with more staining/foxing, ]

In [98]:
#sample value 
notes_df2["notes"][160]

['Two distinct paper types in this book',
 ' This sample taken from a much darker page',
 '']

In [124]:
#create a dictionary where the keys are the phrases and the values are the frequency of the phrase

freq_dict = {}

for index, row in notes_df2.iterrows():
    for i in row[1]:
        i = i.lstrip().lower()
        if i not in freq_dict:
            freq_dict[i] = 1
        else:
            freq_dict[i] += 1
            
freq_dict

{'gatherings have conspicuously different degrees of yellowing / page discoloration:\nthis sample from a gathering with significant yellowing': 1,
 '': 126,
 'gatherings have conspicuously different degrees of yellowing / page discoloration:\nthis sample from a gathering with much lighter paper': 1,
 'sections have very different degrees of staining/foxing:\nthis sample from a page within a section with significant staining': 1,
 'sections have very different degrees of staining/foxing:\nthis sample from a page within a section with less damaged paper': 1,
 'sections have very different degrees of staining/foxing and yellowing:\nthis sample from a page within a section with significant foxing and yellowing': 1,
 'sections have very different degrees of staining/foxing and yellowing:\nthis sample from a page within a section where the paper is in much better condition': 1,
 "clear paper - makes up most of the book's gatherings": 1,
 'sections have very different degrees of staining/foxi

In [125]:
#turn the dictionary into a pandas df
freq_df = pd.DataFrame(list(freq_dict.items()),columns = ['phrase','frequency'])
freq_df

phrase  frequency
0    gatherings have conspicuously different degree...          1
1                                                             126
2    gatherings have conspicuously different degree...          1
3    sections have very different degrees of staini...          1
4    sections have very different degrees of staini...          1
..                                                 ...        ...
411                                 darker brown stock          1
412                              control: january 2021          1
413                    jan 2021 - six-monthly controls          6
414                            primary textblock paper          1
415                          secondary textblock paper          1

[416 rows x 2 columns]

In [128]:
#sort that df
freq_df= freq_df.sort_values("frequency", ascending=False)
freq_df = freq_df.drop(1) #this was just a white space
freq_df

phrase  frequency
72                       plate         98
43                 cream paper         59
116                     darker         54
36                darker paper         51
167                plate stock         46
..                         ...        ...
122       lighter whiter paper          1
124      cream stock (primary)          1
128       usually sample p 187          1
207         manila card insert          1
415  secondary textblock paper          1

[415 rows x 2 columns]

In [148]:
#playing around with dropping the infrequent phrases, such dropping less than 10
freq_moreThan = freq_df[freq_df.frequency > 10]
freq_moreThan

phrase  frequency
72                                    plate         98
43                              cream paper         59
116                                  darker         54
36                             darker paper         51
167                             plate stock         46
175                  for comparison with cu         45
113                                 lighter         42
251  for comparison with other institutions         40
98                  for comparison with uwl         37
163                 for comparison with asu         32
162                          opened already         30
105                        reverse of plate         30
35                            lighter paper         29
54                                    brown         27
373                              text stock         26
57                                   foxing         26
51                                    cream         25
288                            whiter paper         20
94              for comparison with cornell         20
155                minor foxing near plates         20
58                          textblock paper         20
164                                pf plate         15
237                             brown paper         15
154                          insert at back         15
18                              cream stock         12
365        hammermill laser bond 25% cotton         12
93            reverse of illustration plate         12
119                         textblock stock         11

In [156]:
#import data vis libraries
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
#plot a bar chart of the phrases with a freq above value as described above
plt.figure(figsize=(16,8))
chart = sns.barplot(x="phrase", y="frequency", data=freq_moreThan)
chart.set_xticklabels(chart.get_xticklabels(), rotation=45, horizontalalignment='right')
plt.show()

NameError: name 'plt' is not defined

# Book

In [18]:
# Data: Book

#%%time
# https://www.kaggle.com/jboysen/quick-tutorial-flatten-nested-json-in-pandas

book1 = book.dropna(axis=1, how='all').drop('index', axis=1)

# rename columns
book1.rename(columns={"_id": "book_id","institutionId":"institution_id","catalogId":"catalog_id"}, inplace=True)

# clean id column content
book1['book_id'] = book1['book_id'].str.replace('book:','') #WARNING line
book1['institution_id'] = book1['institution_id'].str.replace('institution:','')
book1['catalog_id'] = book1['catalog_id'].str.replace('catalog:','')

# separate out columns
book2 = book1[['book_id','catalog_id', 'institution_id', 'catalog', 'description', 'batch', 'doubleFold', 'condition']]

# flatten and concatenate
book2['doubleFold'] = book2['doubleFold'].apply(lambda x:x['value'])
catalog_frame = pd.concat(book2['catalog'].apply(lambda x:json_normalize(x)).values.tolist()).reset_index().drop(['index'], axis=1)
description_frame = pd.concat(book2['description'].apply(lambda x:json_normalize(x)).values.tolist()).reset_index().drop(['index'], axis=1)
condition_frame = pd.concat(book2['condition'].apply(lambda x:json_normalize(x)).values.tolist()).reset_index().drop(['index'], axis=1)


book3 = pd.concat([book2, catalog_frame, description_frame, condition_frame], axis=1)

In [19]:
book3

book_id catalog_id institution_id  \
0      00100      00100          00007   
1      00101      00101          00007   
2      00102      00102          00007   
3      00103      00103          00007   
4      00104      00104          00007   
...      ...        ...            ...   
1399   10950      10267          00002   
1400   10951      10268          00002   
1401   10952      10326          00002   
1402   10953      10184          00004   
1403   10954      10267          00004   

                                                catalog  \
0     {'title': 'A Short History of Architecture in ...   
1     {'title': 'Le Condominium Franco-Anglais', 'au...   
2     {'title': 'Symphonies and Their Meaning', 'aut...   
3     {'title': 'The Young People's Story of Archite...   
4     {'title': 'Report of the Board of Commissioner...   
...                                                 ...   
1399  {'title': 'Three Etruscan painted sarcophagi',...   
1400  {'title': 'Russia : her economic past and futu...   
1401  {'title': 'Life of Lord Kitchener', 'author': ...   
1402  {'title': 'Catalogue of bronzes, etc., in Fiel...   
1403  {'title': 'Three Etruscan painted sarcophagi',...   

                                            description batch doubleFold  \
0     {'binding': {'leafAttachment': '', 'material':...     0              
1     {'binding': {'leafAttachment': '', 'material':...     0              
2     {'binding': {'leafAttachment': '', 'material':...     0              
3     {'binding': {'leafAttachment': '', 'material':...     0              
4     {'binding': {'leafAttachment': '', 'material':...     0              
...                                                 ...   ...        ...   
1399  {'binding': {'leafAttachment': 'sewn', 'materi...     3         10   
1400  {'binding': {'leafAttachment': 'sewn', 'materi...     3         10   
1401  {'binding': {'leafAttachment': 'sewn', 'materi...     4         10   
1402  {'binding': {'leafAttachment': 'sewn', 'materi...     3         10   
1403  {'binding': {'leafAttachment': 'sewn', 'materi...     3         10   

                                              condition author.first  \
0     {'lendable': False, 'cover': {'damage': {'worn...                
1     {'lendable': False, 'cover': {'damage': {'worn...                
2     {'lendable': False, 'cover': {'damage': {'worn...                
3     {'lendable': False, 'cover': {'damage': {'worn...                
4     {'lendable': False, 'cover': {'damage': {'worn...                
...                                                 ...          ...   
1399  {'lendable': True, 'deteriorating': False, 'co...                
1400  {'lendable': True, 'deteriorating': False, 'co...                
1401  {'lendable': True, 'deteriorating': False, 'co...                
1402  {'lendable': True, 'deteriorating': False, 'co...                
1403  {'lendable': True, 'deteriorating': False, 'co...                

     author.last  ... textblock.marginalia  textblock.missing.pages  \
0                 ...                False                            
1                 ...                False                            
2                 ...                False                            
3                 ...                False                            
4                 ...                False                            
...          ...  ...                  ...                      ...   
1399              ...                False                            
1400              ...                False                            
1401              ...                False                            
1402              ...                False                            
1403              ...                False                            

     textblock.missing.partialPages textblock.nonUniformEdges  \
0                                                       False   
1                             

In [21]:
book3.columns

Index(['book_id', 'catalog_id', 'institution_id', 'catalog', 'description',
       'batch', 'doubleFold', 'condition', 'author.first', 'author.last',
       'author.sortable', 'confirmed', 'dimensions.height',
       'dimensions.thickness', 'dimensions.width', 'edition', 'enclosures',
       'notes', 'numberPages', 'published.date', 'published.location',
       'published.publisher', 'reboundCollectionBooks',
       'reboundCollectionIncludes', 'sameAsCatalog', 'title', 'volume',
       'binding.collectionOfVolumes', 'binding.edgeDecoration',
       'binding.format', 'binding.leafAttachment', 'binding.material',
       'binding.notes', 'binding.obviousRebinding', 'binding.overallColor',
       'notes', 'textblock.illustrations', 'textblock.letterpress',
       'textblock.notes', 'textblock.obviousMultiplePapers.calendered',
       'textblock.obviousMultiplePapers.glossy',
       'textblock.obviousMultiplePapers.normal', 'textblock.printingInk',
       'textblock.textblockPaper', 'textb